POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "matias",
    "password": "abc123"
}

####
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "user2",
    "password": "abcd12345"
}

####
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "user3",
    "password": "abcd12345"
}