POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testaus",
    "author": "Matias",
    "url": "www.testausta.fi",
    "likes": 5
}

####

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2MzM2YWE2MWM1ZDQzMWQ5ZjFkODE2ZmUiLCJpYXQiOjE2NjQ1MjcwODh9.2he3MKO37Yy0zeR5aR5q2q4nftAvCqtX8zlKBbexPwk

{
    "title": "Testausta 2",
    "author": "ABC",
    "url": "www.testausta2.fi",
    "likes": 3
}

####
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGlhcyIsImlkIjoiNjMzNmFhNWRjNWQ0MzFkOWYxZDgxNmZiIiwiaWF0IjoxNjY0NTI2OTk5fQ.KNYCdNAUtFLnJ3FVMbas1iv6X55lEdxfMvyg6u4PI48

{
    "title": "Lisäys tokenin kanssa",
    "author": "Token",
    "url": "www.token.fi",
    "likes": 9
}